---
project_identifier: catrobat
api_key: 6c9a3f10bd747ea3198c0bb9b651d9ab
base_url: http://api.crowdin.net
base_path: C:/Users/Stefan/git/Catroid/Catroid
preserve_hierarchy: true

files:
  -
   source: '/catroid/res/values/strings.xml'
   translation: '/catroid/res/values-%android_code%/%original_file_name%'
   languages_mapping:
      android_code:
        af: af
        ar: ar
        bs: bs
        ca: ca
        cs: cs
        da: da
        de: de
        el: el
        en: en
        es-ES: es
        fa: fa
        fi: fi
        fr: fr
        hi: hi
        hr: hr
        hu: hu
        it: it
        he: he
        ja: ja
        ko: ko
        nl: nl
        pl: pl
        pt-PT: pt
        ro: ro
        ru: ru
        sk: sk
        sl: sl
        sr: sr
        sv-SE: sv
        tr: tr
        uk: uk
        vi: vi
        zh-CN: zh

   first_line_contains_header: true